# TODO
# general settings
name: RCAN_biosr_ccp_12
model_type: RCANCustom
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: BioSR
    type: BioSRDataset
    phase: train
    dataroot: /group/jug/Anirban/Datasets/BioSR/CCPs_SuperRes/train_crop/
    use_hflip: false
    use_rot: false
    input_mean: 102.429474
    input_std: 3.7435353
    target_mean: 310.15253
    target_std: 2256.7798

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 12  # 3120 images / 12 batch size = 260 iterations per epoch

  val:
    name: BioSR_val
    type: BioSRDataset
    phase: val
    dataroot: /group/jug/Anirban/Datasets/BioSR/CCPs_SuperRes/val_crop/
    use_hflip: false
    use_rot: false
    input_mean: 102.429474
    input_std: 3.7435353
    target_mean: 310.15253
    target_std: 2256.7798

# network structures
network_g:
  type: RCAN_custom
  num_in_ch: 1
  num_out_ch: 1
  num_feat: 64
  num_group: 10
  num_block: 20
  squeeze_factor: 16
  upscale: 1
  res_scale: 1

# training settings
train:
  # ema_decay: 0
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [13000, 19500]  # At epochs 50 and 75 (260*50=13000, 260*75=19500)
    gamma: 0.5

  total_iter: 52000  # 200 epochs * 260 iterations per epoch (3120/12)
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 260  # Validate after every epoch (260 iterations = 1 epoch)
  save_img: false
  # suffix: "reconstruction"  # Optional: custom suffix for saved images

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    loss: # track training loss
      type: calculate_loss

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# logging settings
logger:
  print_freq: 65  # Print four times per epoch (260/4 = 65)
  save_checkpoint_freq: 260  # Save checkpoint after every epoch
  use_tb_logger: true
  wandb:
    project: basicsr
    resume_id: ~
